apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jtl7
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0011-tenant/ci1t-830-0011-app/devfile-sample-jtl7@sha256:cf7f7773529c4df4ba10956b468e04720239c7743fe73cf4981e3acc15f77603
        name: my-nodejs
        resources: {}
status: {}
